db.url=jdbc:postgresql://localhost:5432/epicenter
db.user=postgres
db.password=123
queue.capacity=5000
producer.thread.pool.size=2
consumer.thread.pool.size=4
batch.size=500
shop.entry.target=3000000
type.increase.coefficient=1000
max.stock.quantity=500
